tasks:
  load:
    file: src main resources tasks.csv
  write:
    file: src main resources writetasks.csv
users:
  load:
    file: src main resources users.csv
  write:
    file: src main resources writeusers.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&charSet=UTF8
    username: user
    password: user
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false