tasks:
  load:
    file: src main resources tasks.csv
  write:
    file: src main resources writetasks.csv
users:
  load:
    file: src main resources users.csv
  write:
    file: src main resources writeusers.csv